version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/suresight
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - suresight-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=suresight
    ports:
      - "5432:5432"
    networks:
      - suresight-network

volumes:
  postgres_data:

networks:
  suresight-network: