# deployment/docker-compose.yml

services:
  backend:
    build:
      context: ../
      dockerfile: deployment/backend.Dockerfile
    container_name: suresight_backend
    volumes:
      - ../backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload